<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.0.0" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.0.0" />
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ProyectoNET.Shared\ProyectoNET.Shared.csproj" />
    <ProjectReference Include="..\ProyectoNET.ServiceDefaults\ProyectoNET.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ProyectoNET.WebApp\ProyectoNET.WebApp.csproj" />

  </ItemGroup>

</Project>
