// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoNET.Carreras.API.Data;

#nullable disable

namespace ProyectoNET.Carreras.API.Migrations
{
    [DbContext(typeof(CarrerasDbContext))]
    partial class CarrerasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMaximaParticipantes")
                        .HasColumnType("integer");

                    b.Property<long>("CostoInscripcion")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoCarrera")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenPromocional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.LugarDeEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("LugaresDeEntrega");
                });

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLugarRetiroEquipamientoElegido")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipamientoEntregado")
                        .HasColumnType("boolean");

                    b.Property<int>("LugarRetiroEquipamientoElegidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("LugarRetiroEquipamientoElegidoId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.LugarDeEntrega", b =>
                {
                    b.HasOne("ProyectoNET.Carreras.API.Models.Carrera", "Carrera")
                        .WithMany("LugaresRetiroEquipamiento")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.Participante", b =>
                {
                    b.HasOne("ProyectoNET.Carreras.API.Models.Carrera", "Carrera")
                        .WithMany("Participantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoNET.Carreras.API.Models.LugarDeEntrega", "LugarRetiroEquipamientoElegido")
                        .WithMany()
                        .HasForeignKey("LugarRetiroEquipamientoElegidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("LugarRetiroEquipamientoElegido");
                });

            modelBuilder.Entity("ProyectoNET.Carreras.API.Models.Carrera", b =>
                {
                    b.Navigation("LugaresRetiroEquipamiento");

                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
